spring:
  application:
    name: bluemoon-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: false
    clean-disabled: true
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
springdoc:
  api-docs:
    enabled: false
    version: OPENAPI_3_1
  swagger-ui:
    enabled: false
